### ISSUE TITLE
Cleaner `getVariables`

### ISSUE THREAD

**Issue by lue-bird** [miniBill/elm-generic-dict#4]
Little note that for https://github.com/miniBill/elm-generic-dict/blob/19309062bb6feac45342e2a967bdaeda3bbfaf87/codegen/helpers/CustomDict.elm#L525
you could, as a reference, use https://github.com/lue-bird/elm-review-single-use-type-vars-end-with-underscore/blob/master/src/Help.elm#L175
(this is just from a quick look, I don't know if elm-syntax and elm-codegen are the same in terms of cases etc.)

**Comment by lue-bird** [comment]
sorry, annotation cases / `toSyntaxAnnotation` aren't exposed. You could `toString` and parse to elm-syntax but might be a bit overkill

**Comment by miniBill** [comment]
Yeah, I honestly think it's overkill for now, the current code is ugly but should work. If not I'll make a PR to expose something yeah
